# Generated by Django 5.0 on 2024-07-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0003_rename_message_groupmessage_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='group_name',
            new_name='name',
        ),
    ]
