# Generated by Django 5.0 on 2024-07-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0004_rename_group_name_chatgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
